# Generated by Django 5.0.7 on 2024-11-08 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sped',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
    ]
