# Generated by Django 5.0.7 on 2024-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='logo',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
