# Generated by Django 5.0.7 on 2024-11-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_producer_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='carsp',
        ),
        migrations.AddField(
            model_name='car',
            name='producer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.producer'),
        ),
    ]
